# Docker Compose file which installs Ollama and Open Web UI
# docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:latest
# docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - my_bridge_network
    restart: always

  # open_webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: open-webui
  #   ports:
  #     - "3000:8080"
  #   volumes:
  #     - open-webui:/app/backend/data
  #     # Map the `web_docs` folder here to `/data/docs` in the container
  #     - ./web_docs/:/app/backend/data/docs/
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #     - my_bridge_network
  #   restart: always

networks:
  my_bridge_network:
    driver: bridge

volumes:
  ollama:
  open-webui:
